Homeclick/Models/CollectionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Homeclick.Models
{
    public class CollectionViewModel
    {
        public int id { get; set; }
        public int categoryId { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public string link { get; set; }
    }
}

Homeclick/Models/Extends/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Reflection;
using System.Web;

namespace Homeclick.Models
{
    public partial class Category
    {

        vinabits_homeclickEntities db = new vinabits_homeclickEntities();     

        public static IList<Category_detail> detail(Category category)
        {
            PropertyInfo[] typeInfos = (typeof(Product)).GetProperties();
            IList<Category_detail> child = new List<Category_detail>();
            foreach (PropertyInfo member in typeInfos)
            {
                if (member.CanRead && member.Name == "Category_detail")
                {
                    Dictionary<string, object> details = new Dictionary<string, object>();
                    ICollection<Category_detail> detailList = member.GetValue(category) as ICollection<Category_detail>;
                    child = detailList.ToList<Category_detail>();
                    break;
                }
            }
            return child;
        }

        public Category_detail getDetail(string name)
        {
            return null;
        }

        public object getDetailValue(string name)
        {
            IList<Category_detail> details = this.Category_detail.ToList<Category_detail>();
            if (details.Count == 0)
                return string.Empty;
            Category_detail detail = details.Where<Category_detail>(d => d.name == name).FirstOrDefault();
            if (detail == null)
                return string.Empty;
            return detail.value;
        }

        public IList<T> getItems<T>() where T: class
        {
            var posts = ModelHelper.GetObjectListByCategory<T>(this.Id);
            return posts;
        }

        public IList<Category> getDescendantCategories(CategoryTypes categoryType)
        {
            IList<Category> descendant = new List<Category>();
            string descendantType = categoryType.ToString().ToLower();

            descendant = (from cat in db.Categories
                          where (
                            from product in cat.Products
                            where (from cat2 in product.Categories
                                   where cat2.Id == this.Id
                                   select cat2).Count<Category>() > 0
                            select product).Count<Product>() > 0 && cat.Category_type.name == descendantType
                          select cat).ToList<Category>();
            return descendant;
        }

        public IList<Category> GetCategoryChilds()
        {
            var list = ModelHelper.getChildren<Category>(typeof(Category).Name, typeof(Category).Name,this.Id).OrderBy(o => o.name).ToList();
            var sortedList = list.OrderBy(o => o.Order).ToList();
            return sortedList;
        }

        public string getActionLink()
        {
            string type = "Typology";
            if (this.Category_type.name == "model")
                type = "Model";
            else if (this.Category_type.name == "collection")
                return String.Format("/BoSuuTap/Detail/{0}", this.Id);
            return String.Format("/Category/{1}/{0}",this.Id, type);
        }
    }
}

Homeclick/Models/Extends/Product.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Reflection;
using System.Web;

namespace Homeclick.Models
{
    public partial class Product
    {

        public Dictionary<string, object> ToArray()
        {

            PropertyInfo[] typeInfos = (typeof(Product)).GetProperties();
            Dictionary<string, object> child = new Dictionary<string, object>();
            foreach (PropertyInfo member in typeInfos)
            {
                if (member.CanRead && member.Name == "Product_detail")
                {
                    Dictionary<string, object> details = new Dictionary<string, object>();
                    ICollection<Product_detail> detailList = member.GetValue(this) as ICollection<Product_detail>;
                    foreach (Product_detail detail in detailList)
                    {
                        details.Add(detail.name, detail.value);

                    }
                    child.Add(member.Name, details);
                }

                else if (member.CanRead)
                {
                    child.Add(member.Name, member.GetValue(this));
                }
            }
            return child;

        }

        public Dictionary<string, object> ToArray(Product products)
        {

            PropertyInfo[] typeInfos = (typeof(Product)).GetProperties();
                Dictionary<string, object> child = new Dictionary<string, object>();
                foreach (PropertyInfo member in typeInfos)
                {
                    if (member.CanRead && member.Name == "Product_detail")
                    {
                        Dictionary<string, object> details = new Dictionary<string, object>();
                        ICollection<Product_detail> detailList = member.GetValue(products) as ICollection<Product_detail>;
                        foreach (Product_detail detail in detailList)
                        {
                            details.Add(detail.name, detail.value);

                        }
                        child.Add(member.Name, details);
                    }

                    //else if (member.CanRead)
                    //{
                    //    child.Add(member.Name, member.GetValue(p));
                    //}
                }
                return child;

        }

        public Dictionary<string, object> ToArray(Category products)
        {

            PropertyInfo[] typeInfos = (typeof(Category)).GetProperties();
            Dictionary<string, object> child = new Dictionary<string, object>();
            foreach (PropertyInfo member in typeInfos)
            {
                if (member.CanRead && member.Name == "Category_detail")
                {
                    Dictionary<string, object> details = new Dictionary<string, object>();
                    ICollection<Category_detail> detailList = member.GetValue(products) as ICollection<Category_detail>;
                    foreach (Category_detail detail in detailList)
                    {
                        details.Add(detail.name, detail.value);

                    }
                    child.Add(member.Name, details);
                }

                if (member.CanRead && member.Name == "Category_type")
                {
                    Dictionary<string, object> details = new Dictionary<string, object>();
                    ICollection<Category_type> detailList = member.GetValue(products) as ICollection<Category_type>;
                    foreach (Category_type detail in detailList)
                    {
                        details.Add(detail.name, detail.caption);

                    }
                    child.Add(member.Name, details);
                }

            }
            return child;

        }

        
    }
}

Homeclick/Models/ProjectViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Homeclick.Models
{
    public class ProjectViewModel
    {
        public int id { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public string city { get; set; }
        public int type { get; set; }
        public int statu { get; set; }
    }
}

Homeclick/Controllers/CategoryController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System;
using VCMS.Lib.Models;

namespace Homeclick.Controllers
{
    public class CategoryController : Controller
    {
        public CategoryTypes CategoryType
        {
            get
            {
                return CategoryTypes.Model;
            }
        }

        public ApplicationDbContext db = new ApplicationDbContext();

        public virtual ActionResult _Sidebar()
        {
            var categories = db.Categories.Where(c => c.CategoryTypeId == (int)CategoryType).ToList();
            return PartialView(categories);
        }

        public ActionResult Typologies()
        {
            var typologies = db.Product_Types;
            return View(typologies);
        }
    }

}

Homeclick/Controllers/CollectionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using VCMS.Lib.Models;
using VCMS.Lib.Common;

namespace Homeclick.Controllers
{
    public class CollectionController : Controller
    {
        public CategoryTypes CategoryType { get { return CategoryTypes.Collection; } }
        public ApplicationDbContext db = new ApplicationDbContext();

        public virtual ActionResult _Sidebar()
        {
            var categories = db.Categories.Where(c => c.CategoryTypeId == (int)CategoryType).ToList();
            return PartialView(categories);
        }

        public ActionResult Index()
        {
            var featureCollection = new List<Post>();
            var categories = db.Categories.Where(o => o.CategoryTypeId == (int)CategoryTypes.Collection);
            foreach (var category in categories)
            {
                featureCollection.AddRange(category.Posts.Where(o => o.Featured));
            }
            ViewBag.Slides = db.Categories.Find((int)SlideTypes.Collection).Slides;
            return View(featureCollection);
        }

        public ActionResult Category(int category_id, int? page)
        {
            int pageSize = 8;
            int pageNumber = (page ?? 1);
            var category = db.Categories.Find(category_id);
            var list = category.GetAllPost();
            return View(list.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Detail(int collection_id)
        {
            var collection = db.Posts.Find(collection_id);
            var category = db.Categories.Find(collection.Categories.FirstOrDefault().Id);

            if (category == null || collection == null)
                return HttpNotFound();

            //some other collection
            category.Posts.Remove(collection);
            ViewBag.OtherCollections = category.Posts.PickRandom(3);

            return PartialView(collection);
        }
    }
}

Homeclick/Controllers/JSONController.cs
using Homeclick.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Homeclick.Controllers
{
    public class JSONController : Controller
    {
        vinabits_homeclickEntities db = new Models.vinabits_homeclickEntities();

        public JsonResult _GetRooms(int? layout_id)
        {
            var list = db.ProjectItems.Where(o => o.LockedOut == false && o.ParentId == layout_id).ToList();
            var json = new List<object>();
            foreach (var item in list)
            {
                json.Add(new
                {
                    id = item.Id,
                    name = item.Name,
                    areaCoords = item.AreaCoords
                });
            }
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        public JsonResult _Collections(int? room_id, int? layout_id)
        {
            var list = new List<ProjectLayout_Collection>();
            if (room_id != null)
                list = db.ProjectLayout_Collections.Where(o => o.LockedOut == false && o.LayoutId == room_id).ToList();
            else
            {
                var temp = db.ProjectItems.Where(o => o.ParentId == layout_id).ToList();
                foreach (var item in temp)
                {
                    var v = db.ProjectLayout_Collections.Where(o => o.LockedOut == false && o.LayoutId == item.Id).ToList();
                    list.AddRange(v);
                }
            }

            var json = new List<object>();
            foreach (var item in list)
            {
                json.Add(new
                {
                    id = item.Id,
                    roomId = item.LayoutId,
                    name = item.Name,
                    image = item.Image,
                    area = item.Area
                });
            }
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetStates(int city_id)
        {
            var states = db.States.Where(o => o.CityId == city_id);
            var jsonResult = new List<object>();
            foreach (var state in states)
            {
                jsonResult.Add(new
                {
                    id = state.Id,
                    name = state.Name,
                    city = state.CityId
                });
            }
            return Json(jsonResult, JsonRequestBehavior.AllowGet);
        }
    }
}

Homeclick/Controllers/ProjectController.cs
using VCMS.Lib.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VCMS.Lib.Common;

namespace Homeclick.Controllers
{
    public class ProjectController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult _Sidebar()
        {
            var categories = db.Categories.Where(o => o.CategoryTypeId == (int)CategoryTypes.ProjectType);
            ViewData["cities"] = db.Cities;
            ViewData["states"] = db.Districts;

            return PartialView(categories);
        }

        public ActionResult Index(int? category_id)
        {
            var viewModel = db.Projects.Where(o => o.Status);
            return View(viewModel);
        }

        public ActionResult Category(int category_id)
        {
            return View();
        }

        public ActionResult Map()
        {
            ViewBag.MetaKeyword = "homeclick";
            ViewBag.MetaDescription = "project";
            var types = db.Categories.Where(o => o.CategoryParentId == 28);
            var cities = db.Cities.ToList();

            ViewBag.ProjectTypes = types;
            ViewBag.Cities = cities;

            var categories = db.Categories.Where(o => o.CategoryTypeId == (int)CategoryTypes.ProjectType);
            ViewBag.Categories = categories;

            return View();
        }

        public ActionResult Details(int? category_id, int? project_id)
        {
            var project = db.Projects.Find(project_id);
            return View(project);
        }

        public ActionResult Collection(int? collection_id)
        {
            var collection = db.Posts.Find(collection_id);
            if (collection != null)
                return PartialView(collection);
            return HttpNotFound();
        }

        public JsonResult CollectionImages(int? collection_id)
        {
            var list = new List<string>();
            if (collection_id != null)
            {
                var collection = db.Posts.Find(collection_id);
                foreach (var item in collection.Post_Details.Where(o => o.Name == "popupImages"))
                {
                    list.Add(item.Value);
                }
            }
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        [AjaxChildActionOnly]
        public PartialViewResult _RenderRooms(int? floor_id)
        {
            var floor = db.Floors.Find(floor_id);
            var rooms = floor.Rooms;
            return PartialView(rooms);
        }

        [HttpPost]
        public JsonResult GetCollections(int room_id)
        {
            var room = db.Rooms.Find(room_id);
            var result = new List<object>();
            foreach (var collection in room.Collections)
            {
                result.Add(new { id = collection.Id, name = collection.Title, image = collection.ImageFile.FullFileName });
            }
            return Json(result);
        }

        [HttpGet]
        public JsonResult GetProjectsData(int? category_id)
        {
            IEnumerable<Project> projects;

            projects = category_id == null || category_id == -1 ? db.Projects.ToList() :
                                db.Projects.Where(o => o.CategoryId == category_id).ToList();

            var json = new List<object>();
            foreach (var project in projects)
            {
                json.Add(new
                {
                    id = project.Id,
                    name = project.Name,
                    image = project.PreviewImage.FullFileName,
                    address = project.Address,
                    state = project.DistrictId,

                    statu = Convert.ToInt32(project.Status),
                    type = project.CategoryId,
                });
            }
            return Json(json, JsonRequestBehavior.AllowGet);
        }
    }
}

Homeclick/Views/Project(old)/Category(old).cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_SharedLayout.cshtml";
    var url = "";
}

<div class="main-body row">
    <div id="projectsGrid" class="clearfix">

    </div>

    <div id="projectsLoading" class="loading" style="display: none;">
        <img class="loadingImg" src="@url/Content/loading.gif" height="150" width="150" />
    </div>
</div>

@section breadcrumb {
    <ul>
        <li><a href="../">Home</a></li>
        <li>Dự án</li>
    </ul>
}

@section styles {
    <link href="~/Content/Project.css" rel="stylesheet" />
    <style>
    </style>
}

@section scripts {
    <script type='text/javascript' src="~/Scripts/Plugins/jlinq/jlinq.js"></script>
    <script type='text/javascript' src="~/Scripts/Plugins/Map/map.js"></script>

    <script>

        (function ($) {
            $.fn.toggleAtrr = function (atrr) {
                if ($(this).attr('checked'))
                    $(this).removeAttr('checked')
                else
                    $(this).attr('checked', 'checked');
            };
        })(jQuery);

        var jsonData = [];
        var typeSelection = $('#projectTypeSelection');
        var citySelection = $('#projectCitiesSelection');
        var statesSelection = $('#statesSelection');

        var statuCheckers = [
            $('#statu-true'),
            $('#statu-false')
        ];

        var filterTextBox = $('#filterTextBox');
        var filterButton = $('#filterButton');
        var projectsGrid = $('#projectsGrid');

        typeSelection.bind("change", function () {
            selectChanged();
        });

        citySelection.bind("change", function () {
            //Get states
            statesSelection.html('');
            var item = '<option selected value="">Quận</option>';
            statesSelection.append(item)

            if ($(this).val()) {
                var url = '@Url.Action("GetStates", "JSON")';
                var states = $.getJsonFromUrl(url, { 'city_id': citySelection.val() })

                for (var i = 0; i < states.length; i++) {
                    item = '<option value="' + states[i].id + '">' + states[i].name + '</option>';
                    statesSelection.append(item);
                }
            }

            selectChanged();
        });

        statesSelection.bind("change", function () {

            selectChanged();
        });

        statuCheckers[0].bind("change", function () {
            $(this).toggleAtrr('checked')
            selectChanged();
        });

        statuCheckers[1].bind("change", function () {
            $(this).toggleAtrr('checked')
            selectChanged();
        });

        filterButton.bind("click", function () {
            selectChanged();
        });

        filterTextBox.bind("change", function () {
            selectChanged();
        });

        function selectChanged() {
            var typeSelectionVal = typeSelection.val();
            var citySelectionVal = citySelection.val();
            var statesSelectionVal = statesSelection.val();
            var filterTextBoxVal = filterTextBox.val();

            var result = jsonData;

            if (typeSelectionVal)
                result = filterByField(result, 'type', typeSelectionVal)

            if (citySelectionVal)
                result = filterByField(result, 'city' ,citySelectionVal)

            if (statesSelectionVal)
                result = filterByField(result, 'state', statesSelectionVal)

            if (statuCheckers[0].attr('checked') && statuCheckers[1].attr('checked')) {
            }
            else if (statuCheckers[0].attr('checked')) {
                result = filterByField(result, 'statu', statuCheckers[0].val())
            }
            else if (statuCheckers[1].attr('checked')) {
                result = filterByField(result, 'statu', statuCheckers[1].val())
            }
            else {
                return;
            }

            if (filterTextBoxVal) {
                var manageradiorel = $('input[name="a"]:checked').val();
                result = filterByField(result, manageradiorel, filterTextBoxVal)
            }

            showProjects(result);
        }

        function showProjects(data) {
            projectsGrid.html('');
            var baseLink = '@Url.Action("Details")';
            for (var i = 0; i < data.length; i++) {
                var link = '@Url.Action("Details")' + '?category_id=' + data[i].type + '&project_id=' + data[i].id;
                var item = '<div class="project-tile  col-xs-6 col-md-4">' +
                    '<div class="project-tile-image fullscreener fsr-container">' +
                        '<img width="650" height="420" src="' + data[i].image + '" class="attachment-project-image size-project-image wp-post-image fsr-image fsr-hidden" alt="Helsinki-Central-Library">' +
                        '</div>' +
                        '<div class="project-tile-overlay">' +
                            '<h4>' + data[i].name + '</h4>' +
                            '<a href="' + link + '" class="button tiny">Xem chi tiết <i class="fa fa-search" aria-hidden="true"></i></a>' +
                        '</div>' +
                    '</div>';
                projectsGrid.append(item);
            }
        }

        var category_id = '@Request.Params["category_id"]';
        jQuery(document).ready(function ($) {
            var url = '@Url.Action("GetProjectsData", "JSON")'
            var data = $.getJsonFromUrl(url, { 'category_id': category_id });
            jsonData = data;
            showProjects(jsonData);
        });

    </script>
}

Homeclick/Views/Project(old)/Category.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_SharedLayout.cshtml";
    var url = "";
}

<div class="main-body row">
    <div id="projectsGrid" class="clearfix">

    </div>

    <div id="projectsLoading" class="loading" style="display: none;">
        <img class="loadingImg" src="@url/Content/loading.gif" height="150" width="150" />
    </div>
</div>

@section breadcrumb {
    <ul>
        <li><a href="../">Home</a></li>
        <li>Dự án</li>
    </ul>
}

@section styles {
    <link href="~/Content/Project.css" rel="stylesheet" />
    <style>
    </style>
}

@section scripts {
    <script type='text/javascript' src="~/Scripts/Plugins/jlinq/jlinq.js"></script>
    <script type='text/javascript' src="~/Scripts/Plugins/Map/map.js"></script>

    <script>

        (function ($) {
            $.fn.toggleAtrr = function (atrr) {
                if ($(this).attr('checked'))
                    $(this).removeAttr('checked')
                else
                    $(this).attr('checked', 'checked');
            };
        })(jQuery);

        var jsonData = [];
        var typeSelection = $('#projectTypeSelection');
        var citySelection = $('#projectCitiesSelection');
        var statesSelection = $('#statesSelection');

        var statuCheckers = [
            $('#statu-true'),
            $('#statu-false')
        ];

        var filterTextBox = $('#filterTextBox');
        var filterButton = $('#filterButton');
        var projectsGrid = $('#projectsGrid');

        typeSelection.bind("change", function () {
            selectChanged();
        });

        citySelection.bind("change", function () {
            //Get states
            statesSelection.html('');
            var item = '<option selected value="">Quận</option>';
            statesSelection.append(item)

            if ($(this).val()) {
                var url = '@Url.Action("GetStates", "JSON")';
                var states = $.getJsonFromUrl(url, { 'city_id': citySelection.val() })

                for (var i = 0; i < states.length; i++) {
                    item = '<option value="' + states[i].id + '">' + states[i].name + '</option>';
                    statesSelection.append(item);
                }
            }

            selectChanged();
        });

        statesSelection.bind("change", function () {

            selectChanged();
        });

        statuCheckers[0].bind("change", function () {
            $(this).toggleAtrr('checked')
            selectChanged();
        });

        statuCheckers[1].bind("change", function () {
            $(this).toggleAtrr('checked')
            selectChanged();
        });

        filterButton.bind("click", function () {
            selectChanged();
        });

        filterTextBox.bind("change", function () {
            selectChanged();
        });

        function selectChanged() {
            var typeSelectionVal = typeSelection.val();
            var citySelectionVal = citySelection.val();
            var statesSelectionVal = statesSelection.val();
            var filterTextBoxVal = filterTextBox.val();

            var result = jsonData;

            if (typeSelectionVal)
                result = filterByField(result, 'type', typeSelectionVal)

            if (citySelectionVal)
                result = filterByField(result, 'city' ,citySelectionVal)

            if (statesSelectionVal)
                result = filterByField(result, 'state', statesSelectionVal)

            if (statuCheckers[0].attr('checked') && statuCheckers[1].attr('checked')) {
            }
            else if (statuCheckers[0].attr('checked')) {
                result = filterByField(result, 'statu', statuCheckers[0].val())
            }
            else if (statuCheckers[1].attr('checked')) {
                result = filterByField(result, 'statu', statuCheckers[1].val())
            }
            else {
                return;
            }

            if (filterTextBoxVal) {
                var manageradiorel = $('input[name="a"]:checked').val();
                result = filterByField(result, manageradiorel, filterTextBoxVal)
            }

            showProjects(result);
        }

        function showProjects(data) {
            projectsGrid.html('');
            var baseLink = '@Url.Action("Details")';
            for (var i = 0; i < data.length; i++) {
                var link = '@Url.Action("Details")' + '?category_id=' + data[i].type + '&project_id=' + data[i].id;
                var item = '<div class="project-tile  col-xs-6 col-md-4">' +
                    '<div class="project-tile-image fullscreener fsr-container">' +
                        '<img width="650" height="420" src="' + data[i].image + '" class="attachment-project-image size-project-image wp-post-image fsr-image fsr-hidden" alt="Helsinki-Central-Library">' +
                        '</div>' +
                        '<div class="project-tile-overlay">' +
                            '<h4>' + data[i].name + '</h4>' +
                            '<a href="' + link + '" class="button tiny">Xem chi tiết <i class="fa fa-search" aria-hidden="true"></i></a>' +
                        '</div>' +
                    '</div>';
                projectsGrid.append(item);
            }
        }

        var category_id = '@Request.Params["category_id"]';
        jQuery(document).ready(function ($) {
            var url = '@Url.Action("GetProjectsData", "JSON")'
            var data = $.getJsonFromUrl(url, { 'category_id': category_id });
            jsonData = data;
            showProjects(jsonData);
        });

    </script>
}

Homeclick/Views/Project(old)/Detail.cshtml
@{
    Layout = "~/Views/Shared/_Layout_Project.cshtml";
}

Homeclick/Views/Project(old)/_Collections.cshtml
@model IEnumerable<Homeclick.Models.ProjectLayout_Collection>
@{
    var url = "";
}

    @foreach (var item in Model)
    {
        <div class="card-l col-xs-6 col-sm-4 col-md-4 col-lg-4">
            <div class="card card-shadow">
                <div>
                    <a class="layoutItem" onclick="CollectionClick(@item.Id)">
                        <img style="height:auto; width:100%" src="@url/@item.Image" alt="@item.Description" />
                    </a>
                </div>
                <div class="card-title">
                    <span>Thumbnail</span>
                </div>
            </div>
        </div>
    }

Homeclick/Views/Project(old)/_ProductsTable.cshtml
@model IEnumerable<Homeclick.Models.ProjectLayout_Collection_Product_Link>
   @{
       var info = System.Globalization.CultureInfo.GetCultureInfo("vi-VN");
       var total = 0;
       foreach (var item in Model)
       {
           total += item.TotalValue;
       }

   }
<h3 class="section-header table-section-header">Sản phẩm trong Set</h3>
<div class="total-html">Tổng: <span>@total.ToString("#,###", info.NumberFormat)</span>vnđ</div>
<div class="category-product-detail clearfix" style="display:block;">

    <table class="table-striped col-xs-12 table-product-detail">
        <thead>
            <tr>
                <th>Sản phẩm</th>
                <th>Số lượng</th>
                <th>Đơn giá</th>
                <th>Tổng</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.ProductName
                    </td>
                    <td>
                        @item.Quantity
                    </td>
                    <td>
                        @item.ProductValue.ToString("#,###", info.NumberFormat) vnđ
                    </td>
                    <td>
                        @item.TotalValue.ToString("#,###", info.NumberFormat) vnđ
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>